services:
  postgres:
    image: postgres:16-alpine
    container_name: digital_wallet_db
    environment:
      POSTGRES_DB: digital_wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d digital_wallet"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: digital_wallet_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/digital_wallet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
