services:
  postgres:
    image: postgres:16-alpine
    container_name: digital_wallet_php_db
    environment:
      POSTGRES_DB: digital_wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    volumes:
      - pgdata_php:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d digital_wallet"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: digital_wallet_php_app
    ports:
      - "8001:8080"
    environment:
      APP_KEY: base64:9kQeF1MxP7vL3nR5tW8yZ2aB4cD6eF0gH2iJ4kL6mN=
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: digital_wallet
      DB_USERNAME: postgres
      DB_PASSWORD: root
      JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      JWT_EXPIRATION: "86400000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata_php:
